[versions]
micronaut-docs = "2.0.0"
micronaut = "4.10.2"
micronaut-test = "4.7.0"

groovy = "4.0.24"
spock = "2.3-groovy-4.0"

neo4j-java-driver = "5.28.10"

[libraries]
neo4j-bolt = { module = "org.neo4j.driver:neo4j-java-driver", version.ref = "neo4j-java-driver" }